# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsHeadlineDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git', :tag => '4.8.0'
  
  # Pods for NewsHeadlineDemo

  target 'NewsHeadlineDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsHeadlineDemoUITests' do
    # Pods for testing
  end

end
